[package]
name = "callcode-orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.5.0"
lapin = "2.5.0"
regex = "1.11.1"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.42.0", features = ["full"] }
