# .github/workflows/lint-build.yml

name: Lint and Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-build:
    name: Lint and Build Monorepo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack 
        run: corepack enable

      - name: Install root dependencies
        run: npm install

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install API dependencies
        working-directory: apps/api
        run: pnpm install

      - name: Install Web dependencies
        working-directory: apps/web
        run: pnpm install

      - name: Inject .env from secret to apps/api
        run: |
          echo "${{ secrets.ENV_FILE }}" > apps/api/.env.production
          cp apps/api/.env.production apps/api/.env

      - name: Lint code
        run: npm run lint

      - name: Build apps and packages
        run: npm run build
